### ISSUE TITLE
BRD - components in wrong place

### ISSUE THREAD

**Issue by direstraits96** [OpenBoardView/OpenBoardView#265] opened 2022-10-29 22:20 UTC
Components are in the wrong place. Works file on BoardViewer.
openboardview-9.90.0-win32 -> BUG
openboardview-9.0.0.exe -> BUG
openboardview-8.95.2-win32 -> OK
openboardview-8.0.exe -> Not Supported

BRD File: https://mega.nz/file/9G4hXS4A#-WlGMH4mKO5mo_lCQKmTA7BJ9Ub6Hmb4uPeMztAz-tM

**Comment by piernov** [comment] 2022-10-31 12:34
This should be fixed on the master branch already.
Behaviour is a little different than 8.95.2 since the outline of a component (even SMD) will show up on both sides if the component has pins on both sides. (could look weird but this is expected behaviour, not sure which solution would look better)

**Closed** 2023-03-17 10:52 UTC
